# Generated by Django 5.1.1 on 2024-09-23 10:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0005_description_alter_product_img'),
    ]

    operations = [
        migrations.DeleteModel(
            name='description',
        ),
    ]
