# Generated by Django 5.1.1 on 2024-09-23 10:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0007_description'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Description',
        ),
    ]
